# Generated by Django 5.2.4 on 2025-07-26 13:07

import django.db.models.deletion
import form_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('personal', 'Personal Tax Form'), ('business', 'Business Tax Form')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('boolean', 'Boolean'), ('select', 'Select'), ('textarea', 'Textarea'), ('json', 'JSON Array'), ('encrypted', 'Encrypted Text'), ('signature', 'Digital Signature')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('validation_rules', models.JSONField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_app.formsection')),
            ],
            options={
                'ordering': ['order', 'question_key'],
                'unique_together': {('section', 'question_key')},
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='form_app.formtype'),
        ),
        migrations.CreateModel(
            name='TaxFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_info', models.JSONField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.formtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.formsection')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_data', to='form_app.taxformsubmission')),
            ],
            options={
                'ordering': ['section__order'],
            },
        ),
        migrations.CreateModel(
            name='FormAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='form_app.taxformsubmission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateTimeField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('encrypted_value', form_app.models.EncryptedField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.formquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='form_app.taxformsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='DependentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', form_app.models.EncryptedField()),
                ('relationship', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('months_lived_with_you', models.PositiveIntegerField()),
                ('is_full_time_student', models.BooleanField(default=False)),
                ('child_care_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='form_app.taxformsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CharitableContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charitable_contributions', to='form_app.taxformsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('initial', models.CharField(blank=True, max_length=5)),
                ('last_name', models.CharField(max_length=100)),
                ('ssn', form_app.models.EncryptedField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('work_phone', models.CharField(max_length=20)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owners', to='form_app.taxformsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_placed_in_service', models.DateField()),
                ('total_miles', models.PositiveIntegerField()),
                ('business_miles', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='form_app.taxformsubmission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formsection',
            unique_together={('form_type', 'section_key')},
        ),
        migrations.AddIndex(
            model_name='taxformsubmission',
            index=models.Index(fields=['user', 'status'], name='form_app_ta_user_id_26e24e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxformsubmission',
            index=models.Index(fields=['form_type', 'created_at'], name='form_app_ta_form_ty_7ab869_idx'),
        ),
        migrations.AddIndex(
            model_name='taxformsubmission',
            index=models.Index(fields=['status', 'created_at'], name='form_app_ta_status_e4110b_idx'),
        ),
        migrations.AddIndex(
            model_name='taxformsubmission',
            index=models.Index(fields=['submission_date'], name='form_app_ta_submiss_dd3986_idx'),
        ),
        migrations.AddIndex(
            model_name='formsectiondata',
            index=models.Index(fields=['submission', 'section_key'], name='form_app_fo_submiss_7a32b1_idx'),
        ),
        migrations.AddIndex(
            model_name='formsectiondata',
            index=models.Index(fields=['section_key'], name='form_app_fo_section_607470_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formsectiondata',
            unique_together={('submission', 'section')},
        ),
        migrations.AddIndex(
            model_name='formauditlog',
            index=models.Index(fields=['submission', 'timestamp'], name='form_app_fo_submiss_451931_idx'),
        ),
        migrations.AddIndex(
            model_name='formauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='form_app_fo_user_id_cc8b60_idx'),
        ),
        migrations.AddIndex(
            model_name='formauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='form_app_fo_action_661f78_idx'),
        ),
        migrations.AddIndex(
            model_name='formanswer',
            index=models.Index(fields=['submission', 'question_key'], name='form_app_fo_submiss_e0e602_idx'),
        ),
        migrations.AddIndex(
            model_name='formanswer',
            index=models.Index(fields=['question', 'created_at'], name='form_app_fo_questio_6b18d0_idx'),
        ),
        migrations.AddIndex(
            model_name='formanswer',
            index=models.Index(fields=['question_key'], name='form_app_fo_questio_326666_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formanswer',
            unique_together={('submission', 'question')},
        ),
        migrations.AddIndex(
            model_name='dependentinfo',
            index=models.Index(fields=['submission'], name='form_app_de_submiss_0396c0_idx'),
        ),
        migrations.AddIndex(
            model_name='businessownerinfo',
            index=models.Index(fields=['submission'], name='form_app_bu_submiss_45de95_idx'),
        ),
    ]
