# Generated by Django 5.2.4 on 2026-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='prior_year_return',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
