# Generated by Django 5.2.4 on 2026-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_alter_clientprofile_prior_year_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_first_year',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='prior_year_return',
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='is_first_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='prior_year_return',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
