# Generated by Django 5.2.4 on 2026-03-16 19:19

import uuid
from django.db import migrations, models


def populate_identifiers(apps, schema_editor):
    UserProfile = apps.get_model('form_app', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.identifier = uuid.uuid4()
        profile.save(update_fields=['identifier'])


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_clientbusiness_per_business_fields'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='userprofile',
            name='identifier',
            field=models.UUIDField(null=True, editable=False),
        ),
  
        migrations.RunPython(populate_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
