# Generated by Django 5.2.4 on 2026-03-26 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0008_userprofile_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatePlanningSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, help_text='Last step the client was on')),
                ('step1_personal', models.JSONField(blank=True, default=dict, verbose_name='Step 1 — Personal Information')),
                ('step2_heirs_legal', models.JSONField(blank=True, default=dict, verbose_name='Step 2 — Heirs & Legal')),
                ('step3_distribution', models.JSONField(blank=True, default=dict, verbose_name='Step 3 — Trust Distribution')),
                ('step4_financials', models.JSONField(blank=True, default=dict, verbose_name='Step 4 — Financial, Business & Property')),
                ('staff_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estate Planning Submission',
                'verbose_name_plural': 'Estate Planning Submissions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='form_app_es_user_id_19c33b_idx'), models.Index(fields=['status', 'updated_at'], name='form_app_es_status_59dba0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user',), name='unique_draft_per_user_estate')],
            },
        ),
    ]
