# Generated by Django 5.2.4 on 2026-03-26 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0009_estateplanningsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOCode',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO Code',
                'verbose_name_plural': 'SSO Codes',
                'indexes': [models.Index(fields=['code', 'used'], name='form_app_ss_code_913b5c_idx')],
            },
        ),
    ]
