# Generated by Django 5.2.3 on 2025-06-30 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('monetary_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pipeline_id', models.CharField(max_length=50)),
                ('pipeline_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline_stage_id', models.CharField(max_length=50)),
                ('pipeline_stage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('contact_id', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('location_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
