# Generated by Django 5.2.4 on 2025-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_userfinancedata_tab_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfinancedata',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='userfinancedata',
            name='income',
        ),
        migrations.RemoveField(
            model_name='userfinancedata',
            name='tab_name',
        ),
        migrations.AddField(
            model_name='userfinancedata',
            name='finance_data',
            field=models.JSONField(default=dict),
        ),
    ]
