# Generated by Django 5.2.4 on 2025-08-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='drafted', max_length=20),
        ),
    ]
