# Generated by Django 5.2.4 on 2025-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_surveysubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='form_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('rental', 'Rental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('rental', 'Rental')], default='drafted', max_length=20),
        ),
    ]
