# Generated by Django 5.2.4 on 2025-10-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_alter_surveysubmission_form_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='form_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
