# Generated by Django 5.2.4 on 2026-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_add_flip_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('submitted', 'Submitted')], default='drafted', max_length=20),
        ),
    ]
